// Generated by scripts/theme.mjs from https://tweakcn.com/r/themes/violet-bloom.json
export const themeFontHrefs: string[] = [
  "https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700&display=swap",
  "https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;500;600;700&display=swap",
  "https://fonts.googleapis.com/css2?family=Lora:wght@400;500;600;700&display=swap"
]
