#!/usr/bin/env node
// Switch the app's shadcn/ui theme to any tweakcn theme.
//
//   pnpm theme violet-bloom
//   pnpm theme https://tweakcn.com/r/themes/violet-bloom.json
//   pnpm theme https://tweakcn.com/editor/theme?theme=violet-bloom
//
// Writes app/theme.css (the CSS variables) and app/theme-fonts.ts (the Google
// Fonts the theme names). Nothing else in the app hard-codes theme values.
import { writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const arg = process.argv[2]
if (!arg) {
  console.error('Usage: pnpm theme <tweakcn theme name | registry URL | editor URL>')
  process.exit(1)
}

function registryUrl(input) {
  if (!/^https?:/.test(input)) return `https://tweakcn.com/r/themes/${input}.json`
  const url = new URL(input)
  const fromEditor = url.searchParams.get('theme')
  if (fromEditor) return `https://tweakcn.com/r/themes/${fromEditor}.json`
  return input
}

const url = registryUrl(arg)
const res = await fetch(url)
if (!res.ok) {
  console.error(`Could not fetch ${url}: ${res.status} ${res.statusText}`)
  process.exit(1)
}
const item = await res.json()
const vars = item.cssVars ?? {}
const light = { ...(vars.theme ?? {}), ...(vars.light ?? {}) }
const dark = vars.dark ?? {}
if (!Object.keys(light).length) {
  console.error(`${url} has no cssVars: is it a shadcn registry theme?`)
  process.exit(1)
}

const block = (selector, entries) =>
  `${selector} {\n${Object.entries(entries)
    .map(([k, v]) => `  --${k}: ${v};`)
    .join('\n')}\n}\n`

const css =
  `/* Generated by scripts/theme.mjs from ${url}\n * Do not edit by hand: run \`pnpm theme <name>\` to switch themes. */\n\n` +
  block(':root', light) +
  '\n' +
  block('.dark', dark)
await writeFile(join(root, 'app/theme.css'), css)

// Google Fonts for the first family of each stack, unless it's a system font.
const SYSTEM = new Set(
  [
    'ui-sans-serif', 'ui-serif', 'ui-monospace', 'system-ui', 'sans-serif', 'serif', 'monospace',
    '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Helvetica', 'Helvetica Neue', 'Arial',
    'Georgia', 'Times New Roman', 'Times', 'Courier New', 'Courier', 'Menlo', 'Monaco',
    'Consolas', 'SFMono-Regular', 'SF Mono', 'Cambria', 'Liberation Mono',
  ].map((f) => f.toLowerCase()),
)
const families = [...new Set(
  ['font-sans', 'font-mono', 'font-serif']
    .map((key) => light[key] ?? dark[key])
    .filter(Boolean)
    .map((stack) => stack.split(',')[0].trim().replace(/^['"]|['"]$/g, ''))
    .filter((family) => family && !SYSTEM.has(family.toLowerCase())),
)]

const hrefs = []
for (const family of families) {
  const base = `https://fonts.googleapis.com/css2?family=${family.replace(/ /g, '+')}`
  const withWeights = `${base}:wght@400;500;600;700&display=swap`
  const ok = await fetch(withWeights).then((r) => r.ok, () => false)
  hrefs.push(ok ? withWeights : `${base}&display=swap`)
}
await writeFile(
  join(root, 'app/theme-fonts.ts'),
  `// Generated by scripts/theme.mjs from ${url}\n` +
    `export const themeFontHrefs: string[] = ${JSON.stringify(hrefs, null, 2)}\n`,
)

console.log(`Theme set to ${item.name ?? url}`)
console.log(`  app/theme.css: ${Object.keys(light).length} light, ${Object.keys(dark).length} dark variables`)
console.log(`  fonts: ${families.join(', ') || 'system only'}`)
